In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import nibabel as nib
import numpy as np
import os
import pathlib

In [3]:
base_img_path = '/content/drive/MyDrive/TCIA/nnUNet/nnUNet_raw/Dataset501_Glioblastoma/labelsTr/'
tr_label_files = os.listdir(base_img_path)
tr_label_files.sort()
# print(tr_label_files)
print(len(tr_label_files))

117


In [4]:
for file in tr_label_files:

  file_name = base_img_path + file
  # Load image
  img = nib.load(file_name)
  print("-"*100)
  print ("Patient label file: ", file)

  # Store image as a numpy array
  img_data = img.get_fdata()

  # Check array min, max and unique values for image label values
  print("Before label check")
  print(np.amin(img_data),np.amax(img_data))
  print(np.unique(img_data))

----------------------------------------------------------------------------------------------------
Patient label file:  100.nii.gz
Before label check
0.0 4.0
[0. 1. 2. 4.]
----------------------------------------------------------------------------------------------------
Patient label file:  102.nii.gz
Before label check
0.0 4.0
[0. 1. 2. 4.]
----------------------------------------------------------------------------------------------------
Patient label file:  105.nii.gz
Before label check
0.0 4.0
[0. 1. 2. 4.]
----------------------------------------------------------------------------------------------------
Patient label file:  106.nii.gz
Before label check
0.0 4.0
[0. 1. 2. 4.]
----------------------------------------------------------------------------------------------------
Patient label file:  107.nii.gz
Before label check
0.0 4.0
[0. 1. 2. 4.]
----------------------------------------------------------------------------------------------------
Patient label file:  108.nii.

In [5]:
for file in tr_label_files:

  file_name = base_img_path + file
  # Load image
  img = nib.load(file_name)
  print("-"*100)
  print ("Patient label file: ", file)

  # Store image as a numpy array
  img_data = img.get_fdata()

  # Check array min, max and unique values for image
  print("Before label check")
  print(np.amin(img_data),np.amax(img_data))
  print(np.unique(img_data))

  # Where label is 4, reset it to 3 so nnUnet doesnt complain about non-consecutive labels
  img_data[(img_data == 4.0)] = 3

  # Check min, max and unique values again
  print("After label conversion")
  print(np.amin(img_data),np.amax(img_data))
  print(np.unique(img_data))

  # Convert array back to Nii image
  new_img = nib.Nifti1Image(img_data, img.affine, img.header)

  # Set up new image path
  new_img_path = base_img_path + file
  print ('Saved to: ' + new_img_path)
  # Save image to out_dir_path
  nib.save(new_img, new_img_path)

----------------------------------------------------------------------------------------------------
Patient label file:  100.nii.gz
Before label check
0.0 4.0
[0. 1. 2. 4.]
After label conversion
0.0 3.0
[0. 1. 2. 3.]
Saved to: /content/drive/MyDrive/TCIA/nnUNet/nnUNet_raw/Dataset501_Glioblastoma/labelsTr/100.nii.gz
----------------------------------------------------------------------------------------------------
Patient label file:  102.nii.gz
Before label check
0.0 4.0
[0. 1. 2. 4.]
After label conversion
0.0 3.0
[0. 1. 2. 3.]
Saved to: /content/drive/MyDrive/TCIA/nnUNet/nnUNet_raw/Dataset501_Glioblastoma/labelsTr/102.nii.gz
----------------------------------------------------------------------------------------------------
Patient label file:  105.nii.gz
Before label check
0.0 4.0
[0. 1. 2. 4.]
After label conversion
0.0 3.0
[0. 1. 2. 3.]
Saved to: /content/drive/MyDrive/TCIA/nnUNet/nnUNet_raw/Dataset501_Glioblastoma/labelsTr/105.nii.gz
-------------------------------------------

MetaData

In [6]:
!pip install batchgenerators

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 718.1 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.4/96.4 kB 1.7 MB/s eta 0:00:00
  Created wheel for batchgenerators: filename=batchgenerators-0.25-py3-none-any.whl size=89008 sha256=16258c9568982daa558860d869ef042a1b6ad649e77726038ce5f25873c4cb85
  Stored in directory: /root/.cache/pip/wheels/9e/b0/1b/40912fb58eb167b86cbc444ddb2e6ba382b248215295f932e2
Successfully built batchgenerators


In [1]:
!pip install nnunetv2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.0/197.0 kB 1.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached argparse-1.4.0-py2.py3-none-any.whl.metadata (2.8 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.4/52.4 MB 16.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 MB 15.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 73.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 83.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 50.5 MB/s eta 0:00:00
Using cached argparse-1.4.0-

In [1]:
# Set up all the parameters required by the metadata generation utility

output_folder = '/content/drive/MyDrive/TCIA/nnUNet/nnUNet_raw/Dataset501_Glioblastoma'
channel_names = {0: 'T1', 1: 'T1GD', 2:'T2', 3: 'FLAIR'}
labels = {'background': 0, 'ET': 1, 'NCR': 2, 'ED': 3}
file_ending = '.nii.gz'
region_class_order = {
  'background': 0,
  'whole tumor': (1, 2, 3),
  'tumor core': (2, 3),
  'enhancing tumor': 3
}
num_training_cases = 117
dataset_name = 'UPENN-GBM'
description = 'UPENN-GBM tumor segmentation'

In [2]:
from nnunetv2.dataset_conversion.generate_dataset_json import generate_dataset_json
generate_dataset_json(output_folder=output_folder,channel_names=channel_names, labels=labels,
                      file_ending=file_ending,region_class_order=region_class_order,
                      num_training_cases=num_training_cases, dataset_name=dataset_name, description=description)